# Task : Session 1
Solve these questions own your own and try to test yourself what you have learned in the session.

Happy Learning!

### Q1 :- Print the given strings as per stated format.

**Given strings**:
```
"Data" "Science" "Mentorship" "Program"
"By" "CampusX"
```
**Output**:
```
Data-Science-Mentorship-Program-started-By-CampusX
```

Concept- [Seperator and End]

In [2]:
print("Data", "Science", "Mentorship", "Program", sep='-', end='-started-')
print("By", "CampusX", sep='-')

Data-Science-Mentorship-Program-started-By-CampusX

### Q2:- Write a program that will convert celsius value to fahrenheit.

In [3]:
c = int(input())
f = (c * 9/5) + 32
print(f)

5
41.0

### Q3:- Take 2 numbers as input from the user.Write a program to swap the numbers without using any special python syntax.

In [4]:
a = int(input())
b = int(input())
temp = a
a = b
b = temp
print(a, b)

15
14
14 15

### Q4:- Write a program to find the euclidean distance between two coordinates.Take both the coordinates from the user as input.

In [ ]:
x1 = int(input("X1"))
y1 = int(input("Y1"))
x2 = int(input("X2"))
y2 = int(input("Y2"))

distance = ((x2 - x1)**2 + (y2 - y1)**2)**0.5
print(distance)

### Q5:- Write a program to find the simple interest when the value of principle,rate of interest and time period is provided by the user.

In [6]:
p = int(input())
r = int(input())
t = int(input())

si = (p * r * t) / 100
print(si)

5
15
24
18.0

### Q6:- Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.

For example:
Input:
heads -> 4
legs -> 12
<br>
Output:
dogs -> 2
chicken -> 2

In [10]:
h = int(input())
l = int(input())
d = (l - 2 * h) // 2
c = h - d
if d >= 0 and c >= 0 and (2 * c + 4 * d == l):
    print("dogs ->", d, "chicken ->", c)
else:
    print("Invalid input!")

4
12
dogs -> 2 chicken -> 2

### Q7:- Write a program to find the sum of squares of first n natural numbers where n will be provided by the user.

In [11]:
n = int(input())
sum_of_squares = sum(i**2 for i in range(1, n+1))
print(sum_of_squares)

5
55

### Q8:- Given the first 2 terms of an Arithmetic Series.Find the Nth term of the series. Assume all inputs are provided by the user.

In [12]:

T1 = int(input("Enter the first term: "))
T2 = int(input("Enter the second term: "))
N = int(input("Enter the term position (N): "))

d = T2 - T1

Tn = T1 + (N - 1) * d

print("Nth term of the arithmetic series is:", Tn)

Enter the first term: 4
Enter the second term: 6
Enter the term position (N): 8
Nth term of the arithmetic series is: 18

### Q9:- Given 2 fractions, find the sum of those 2 fractions.Take the numerator and denominator values of the fractions from the user.

In [13]:
a = int(input())
b = int(input())
c = int(input())
d = int(input())

numerator = (a * d) + (b * c)
denominator = b * d

print(numerator, "/", denominator)

5
4
3
2
22 / 8

### Q10:- Given the height, width and breadth of a milk tank, you have to find out how many glasses of milk can be obtained? Assume all the inputs are provided by the user.



Input:<br>
Dimensions of the milk tank<br>
H = 20cm, L = 20cm, B = 20cm
<br><br>
Dimensions of the glass<br>
h = 3cm, r = 1cm

In [16]:

H = int(input())
L = int(input())
B = int(input())
h = int(input())
r = int(input())

tank_volume = H * L * B
glass_volume = 3.14 * r * r * h

num_glasses = tank_volume // glass_volume

print(num_glasses)

20
20
20
3
1
849.0